# Generated by Django 6.0.2 on 2026-04-13 06:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('tutor', 'Tyutor'), ('dekan', 'Dekan'), ('zam_dekan', 'Zam dekan')], max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('third_name', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol'), ('boshqa', 'Boshqa')], max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='users/images/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('passport_seria', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('workplace', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(default='tutor', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='main.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directions', to='main.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('education_code', models.CharField(max_length=20)),
                ('education_language', models.CharField(max_length=30)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='main.direction')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('third_name', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol'), ('boshqa', 'Boshqa')], max_length=10)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('image_hemis', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('course', models.CharField(max_length=15)),
                ('hemis_id', models.CharField(db_index=True, max_length=13, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_country', models.CharField(blank=True, max_length=50, null=True)),
                ('p_region', models.CharField(blank=True, max_length=50, null=True)),
                ('p_district', models.CharField(blank=True, max_length=50, null=True)),
                ('t_country', models.CharField(blank=True, max_length=50, null=True)),
                ('t_region', models.CharField(blank=True, max_length=50, null=True)),
                ('t_district', models.CharField(blank=True, max_length=50, null=True)),
                ('education_type', models.CharField(choices=[('grant', 'Grant'), ('kontrakt', 'Kontrakt'), ('nomalum', 'Nomalum')], default='nomalum', max_length=30)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='main.student')),
            ],
        ),
    ]
