# Generated by Django 6.0.2 on 2026-05-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='passport_pdf',
            field=models.FileField(blank=True, null=True, upload_to='passport_pdfs/'),
        ),
    ]
