# Generated by Django 6.0.2 on 2026-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dormitory',
            options={'ordering': ['created_at'], 'verbose_name': 'Turar joy', 'verbose_name_plural': 'Turar joylar'},
        ),
        migrations.RenameField(
            model_name='dormitory',
            old_name='building_name',
            new_name='building',
        ),
        migrations.RemoveField(
            model_name='dormitory',
            name='building_phone',
        ),
        migrations.AddField(
            model_name='dormitory',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('own_house', "O'z uyida"), ('relative', 'Qarindoshinikida'), ('rented', 'Ijarada')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='status',
            field=models.BooleanField(),
        ),
    ]
