# Generated by Django 6.0.2 on 2026-03-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familysocialstatus',
            name='unofficial_employment',
        ),
        migrations.AddField(
            model_name='familymember',
            name='unofficial_employment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='work_place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gifted',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gifted/'),
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='health_info/'),
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='languageinfo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='language_info/'),
        ),
        migrations.AlterField(
            model_name='languageinfo',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='languageinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='languageinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='protectionorder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='protection_order/'),
        ),
        migrations.AlterField(
            model_name='reprimand',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reprimand/'),
        ),
        migrations.AlterField(
            model_name='reprimand',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialregistry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='social_registry/'),
        ),
        migrations.AlterField(
            model_name='socialregistry',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='p_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='p_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='p_region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='t_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='t_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='t_latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='t_longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='t_region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
