# Generated by Django 6.0.2 on 2026-04-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.direction'),
        ),
    ]
