# Generated by Django 6.0.2 on 2026-05-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentdetail_passport_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='is_amount',
            field=models.BooleanField(default=False),
        ),
    ]
