# Generated by Django 6.0.2 on 2026-04-23 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dormitory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory', to='main.student'),
        ),
    ]
