# Generated by Django 6.0.2 on 2026-03-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_familysocialstatus_unofficial_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
