# Generated by Django 6.0.2 on 2026-03-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image_full_none',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image_none',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image_full',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
