# Generated by Django 6.0.2 on 2026-04-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='direction',
        ),
    ]
