# Generated by Django 6.0.2 on 2026-05-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_studentdetail_is_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='is_amount_file',
            field=models.FileField(blank=True, null=True, upload_to='amount/'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='is_amount',
            field=models.BooleanField(),
        ),
    ]
