# Generated by Django 6.0.2 on 2026-04-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dormitory_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familysocialstatus',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_social_status', to='main.student'),
        ),
    ]
