# Generated by Django 6.0.2 on 2026-03-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_student_image_full_none_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hemis_id',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
