# Generated by Django 6.0.2 on 2026-05-04 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_studentdetail_is_amount_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='tutor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_directions', to=settings.AUTH_USER_MODEL),
        ),
    ]
