# Generated by Django 6.0.2 on 2026-04-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_familysocialstatus_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprimand',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
