# Generated by Django 6.0.2 on 2026-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reprimand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reprimand',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
