# Generated by Django 6.0.2 on 2026-05-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_direction_tutor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='tutor_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pnfl',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='pnfl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
