# Generated by Django 6.0.2 on 2026-04-24 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_reprimand_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinfo',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='main.student'),
        ),
    ]
