# Generated by Django 6.0.2 on 2026-04-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_healthinfo_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pnfl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
