# Generated by Django 6.0.2 on 2026-04-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_languageinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageinfo',
            name='name',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz'), ('tr', 'Turk'), ('ar', 'Arab'), ('zh', 'Xitoy'), ('hi', 'Hind'), ('fr', 'Fransuz'), ('de', 'Nemis'), ('es', 'Ispan'), ('it', 'Italyan'), ('pt', 'Portugaliya'), ('ja', 'Yapon'), ('ko', 'Koreys'), ('fa', 'Fors'), ('kk', 'Qozoq'), ('ky', "Qirg'iz"), ('tg', 'Tojik'), ('tk', 'Turkman'), ('az', 'Ozarbayjon'), ('ka', 'Gruzin'), ('uk', 'Ukraina'), ('pl', 'Polyak'), ('nl', 'Golland'), ('sv', 'Shved'), ('no', 'Norveg'), ('fi', 'Fin'), ('da', 'Daniya'), ('he', 'Ibroniy'), ('id', 'Indoneziya'), ('ms', 'Malay'), ('th', 'Tailand'), ('vi', 'Vyetnam')], default='uz', max_length=50),
        ),
    ]
